# Generated by Django 6.0.3 on 2026-04-12 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_new', 'طلب جديد'), ('order_status', 'تحديث حالة طلب'), ('order_paid', 'تأكيد دفع'), ('product_approved', 'قبول منتج'), ('product_rejected', 'رفض منتج'), ('store_approved', 'قبول متجر'), ('store_suspended', 'إيقاف متجر'), ('welcome', 'ترحيب'), ('system', 'إشعار نظام'), ('low_stock', 'نفاد مخزون'), ('new_review', 'تقييم جديد')], default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='رابط الإجراء', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
