# Generated by Django 6.0.3 on 2026-04-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='صورة سند الحوالة', null=True, upload_to='orders/receipts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_number',
            field=models.CharField(blank=True, help_text='رقم الحوالة أو سند الدفع', max_length=100),
        ),
    ]
