# Generated by Django 6.0.3 on 2026-04-12 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_order_coupon_code_order_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='آخر 4 أرقام من البطاقة', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed',
            field=models.BooleanField(default=False, help_text='تأكيد استلام الدفع من الإدارة'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='مرجع الدفع الموحد', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_number',
            field=models.CharField(blank=True, help_text='رقم المحفظة المرسل منها', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_transaction_id',
            field=models.CharField(blank=True, help_text='رقم عملية التحويل من المحفظة', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'الدفع عند الاستلام'), ('transfer', 'تحويل بنكي'), ('floosak', 'فلوسك'), ('jawali', 'جوالي'), ('kuraimi', 'كريمي'), ('credit_card', 'بطاقة ائتمان')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('transfer', 'تحويل بنكي'), ('floosak', 'فلوسك'), ('jawali', 'جوالي'), ('kuraimi', 'كريمي')], max_length=20, unique=True)),
                ('account_name', models.CharField(help_text='اسم صاحب الحساب', max_length=255)),
                ('account_number', models.CharField(help_text='رقم الحساب أو المحفظة', max_length=100)),
                ('bank_name', models.CharField(blank=True, help_text='اسم البنك (للتحويل البنكي)', max_length=255)),
                ('instructions', models.TextField(blank=True, help_text='تعليمات الدفع للعميل')),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(default='💳', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
