# Generated by Django 6.0.3 on 2026-04-12 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_card_last_four_order_payment_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='اسم المدينة', max_length=100, unique=True)),
                ('base_cost', models.DecimalField(decimal_places=2, help_text='تكلفة الشحن الأساسية بالريال', max_digits=10)),
                ('per_kg_cost', models.DecimalField(decimal_places=2, default=0, help_text='تكلفة إضافية لكل كيلو', max_digits=10)),
                ('estimated_days_min', models.IntegerField(default=1, help_text='أقل عدد أيام للتوصيل')),
                ('estimated_days_max', models.IntegerField(default=3, help_text='أكثر عدد أيام للتوصيل')),
                ('is_available', models.BooleanField(default=True)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='الحد الأدنى للطلب للشحن المجاني (اتركه فارغاً لعدم وجود شحن مجاني)', max_digits=12, null=True)),
            ],
            options={
                'ordering': ['base_cost'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('carrier', models.CharField(default='YemenMarket Express', help_text='اسم شركة الشحن', max_length=100)),
                ('status', models.CharField(choices=[('preparing', 'قيد التجهيز'), ('picked_up', 'تم الاستلام من البائع'), ('in_transit', 'في الطريق'), ('out_for_delivery', 'خارج للتوصيل'), ('delivered', 'تم التوصيل'), ('returned', 'مرتجع')], default='preparing', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
