# Generated by Django 6.0.3 on 2026-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='ملاحظات الإدارة في حال الرفض أو القبول'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_document',
            field=models.FileField(blank=True, help_text='وثيقة إثبات الهوية أو السجل التجاري', null=True, upload_to='vendors/documents/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='الاشتراكات المميزة للمتاجر'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, help_text='شعار المتجر', null=True, upload_to='vendors/logos/'),
        ),
    ]
