# Generated by Django 6.0.3 on 2026-04-14 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_admin_notes_vendor_id_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('transfer', 'تحويل بنكي'), ('floosak', 'فلوسك'), ('jawali', 'جوالي'), ('kuraimi', 'كريمي'), ('cash', 'استلام نقدي')], max_length=20)),
                ('account_name', models.CharField(help_text='اسم صاحب الحساب', max_length=255)),
                ('account_number', models.CharField(help_text='رقم الحساب أو المحفظة', max_length=100)),
                ('bank_name', models.CharField(blank=True, help_text='اسم البنك (للتحويل البنكي)', max_length=255)),
                ('instructions', models.TextField(blank=True, help_text='تعليمات الدفع للعميل')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['provider'],
                'unique_together': {('vendor', 'provider')},
            },
        ),
    ]
